// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noohsmkygtimtprokbjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vb2hzbWt5Z3RpbXRwcm9rYmp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDAwMzMsImV4cCI6MjA2NDUxNjAzM30.RRYlgTwuuWbQK_yGVVCFT8_Jtx2dx_dNK2iOyeuxlzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);